version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      - pip3 install typing
      - pip3 install awscli --force-reinstall --upgrade
      - pip list
      - wget --quiet https://aqua-binary.s3.amazonaws.com/scannercli
      - chmod +x scannercli
  pre_build:
      commands:
        - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:$TAG .
      # - ./scannercli scan --host $AQUA_URL --user $AQUA_USER --password $AQUA_PASSWORD --local $REPOSITORY_URI:$TAG --no-verify --htmlfile aqua.html
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG